### ISSUE TITLE
可以隱藏直連 Facebook 的連結

### ISSUE THREAD

**Issue by Yukaii** [colorgy/Table#1]
有人密粉專，問說能不能把直接導向 Facebook 的按鈕關閉
![2015-08-13 10 22 17](https://cloud.githubusercontent.com/assets/4230968/9252206/d149a670-4209-11e5-9eff-5bcb30014798.png)

應該要做這個功能啦，
畢竟 Facebook 對每個人意義不同。
直連有點太過了...

姓名、性別隱藏可能也會需要（搬移 FB 的概念）
@Neson 又得爆肝了嗎 XDDD

**Comment by zetavg** [comment]
這樣感覺這個設定需要由 Core 做統一管理，畢竟要把各欄位的隱私權設定切開（就像定義 OAuth 的 scope 那樣）然後 pass 給各串接的 App、Website（思

**Comment by zetavg** [comment]
又或是目前先由 Table 這邊做設定開關連結？
ping @ChengHsuanLiu

**Comment by ChengHsuanLiu** [comment]
我現在是直接在 table user 底下加三個欄位
分別是 courses_table_visibility & fb_visibility &courses_table_visibility_for_guests 這三個 boolean
然後 default 都是 true 然後再去 controller 加一個 update action 讓他們可以自己 update
然後剩下就是前端 if else 判斷

**Comment by ChengHsuanLiu** [comment]
先簡單做一下吧 :D

**Comment by Yukaii** [comment]
兵貴神速

**Comment by zetavg** [comment]
風林火山
