### ISSUE TITLE
Admin 可以自由切換 Organization

### ISSUE THREAD

**Issue by Yukaii** [colorgy/Table#2]
還是可視化比較好除錯
來吧 @ChengHsuanLiu （敲碗敲碗）

**Comment by zetavg** [comment]
其實申請一個帳號（沒認證的），然後隨意設定身份就可以了 XD
![2015-08-17 4 28 43](https://cloud.githubusercontent.com/assets/3784687/9295218/7c5c5b58-4498-11e5-95b3-294b82787828.png)
